name: Publish
on:
  push:
    branches:
    - master
jobs:
  release:
    name: Packages
    if: github.repository == 'DuncanUszkay1/assemblyscript'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        ref: master
    - uses: dcodeIO/setup-node-nvm@master
      with:
        node-version: current
    - name: Install dependencies
      run: npm ci
    - name: Build distribution files
      run: |
        npm run clean
        npm run build
    - name: Test distribution files
      run: npm test
    - name: Make semantic release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: node node_modules/semantic-release/bin/semantic-release.js --unstable
